### ISSUE TITLE
Not recompiling files on change? maybe.....?

### ISSUE THREAD

**Issue by wesleytodd** [luisfarzati/express-babelify-middleware#2]
Im not entirely sure what is going on, but it looks like the files are only being transformed once then kept in memory/cached.

We were previously using the `browserify-middleware` package directly, so my guess is it has something to do with babel caching.  I opened an issue here to see if maybe you know an option to pass to stop this behavior.  I looked around the docs and all I could find was [this](https://babeljs.io/docs/usage/require/#babel-disable-cache) which doesn't seem to do anything in this case since it doesnt use the require hook.

Any ideas on how to get this working?

**Comment by lufzle** [comment]
Sorry for the super delay, did you figure out this?

**Comment by wesleytodd** [comment]
I did not fully to my satisfaction, basically I settled on recompiling every time even if there are no changes.  I haven't looked at it in a while, but as the apps we have using this grow I will probably have to look again.
